### PR TITLE
Release candidate 1 for JanICE API v7

### PR DESCRIPTION
**Pull request by JordanCheney**
This is a comprehensive overhaul of the API based on feedback leading up to and after the release of v6.0. v7 is intended to be the final API release before the end of the Janus program. This release candidate includes a number of new features:

1. The ability to specify a log directory in `janice_initialize` and a function to set the log level
2. A function to query the current configuration of the algorithm
3. A callback implementation for detection on long media iterators
4. A utility implementation of MediaIterator for in-memory buffers
5. A move to pass-by-pointer for basic structures over pass-by-value (#18)
6. Removing typedefs that were obfuscating functionality. Notably JaniceTemplateId and JaniceSimilarity
7. JaniceTemplateId is now a `uint64_t` instead of a `size_t`
8. A function to query the feature vector from a template

Documentation updates will follow shortly. @taa01776 @carlosdcastillo @stephenrawls @mlngan could you please conduct a review at your convenience? The proposed timeline is to have initial feedback by 6/15 and a release by 7/1.

Thanks!
Jordan

### CODE REVIEW

**Comment by taa01776** [comment]
WRT the removal of the JaniceTemplateId and JaniceSimilarity typedefs, I'd be curious to know what the motivation was. In both cases, the use of the typedef makes application code and the API declarations much easier to understand ("this isn't a random potentially large number, it's a template ID"), and can also help the compiler identify programmer errors.
What functionality of a template ID is obfuscated by the typedef, exactly?

**Comment by JordanCheney** [comment]
The motivation was that the purpose ("it's a template ID") can be communicated through the variable name. The typedef obfuscates the additional type information that the variable is unsigned and 64 bit, making the developer do an additional lookup.

**Comment by taa01776** [comment]
I’d argue that this obfuscation is good: the size is sizeof(TemplateId), when  you care; possibly excepting the code that’s generating template IDs in the first place, and the place in the test harness code where you print the thing out, they should be completely opaque. In fact, were I doing this, I’d seriously consider
typedef void *JaniceTemplateId;
to kill off any possibility of accidentally doing arithmetic on them. Type declarations are our friends; we shouldn’t throw information away that the compiler can use, and we shouldn’t count on programmers to pick variable names in their code that match the semantics of the thing being stored.
                -ta

**Comment by taa01776** [comment]
If it isn't already, the default logging level should be part of the API spec.

**Comment by taa01776** [comment]
The JaniceDetectionCallback typedef should include the detection's confidence as one of the parameters. Or, as I originally suggested, just have it take a JaniceDetection, which can include whatever information the implementation chooses.
Is there a spec as to what an error return from the callback means?
Any reason why janice_detect_batch doesn't also have a callback flavor?
Finally, I'm not convinced that the JaniceImage parameter conveys enough information for this to be fully useful: JaniceImage objects don't know where they came from. If there's only a callback for janice_detect, I guess it's workable because the source can be included in the user_data, but if this is extended to batches, as I think it should be, that information is not available. With a callback from batch mode, the callback will also need to know whether it's dealing with a video or with an image: since the frame number is unsigned, there's no way to distinguish by, e.g., setting the frame number to -1 for images.

**Comment by taa01776** [comment]
I still argue, as mentioned in #48, that there should be a callback available for enrollment calls. Enrolling all of the detections from a set of videos can take a long time, it's easy to come up with use cases where some processing could be done on the templates as they're created, rather than waiting for the whole batch.

**Comment by JordanCheney** [comment]
@taa01776 My biggest issue with callbacks as proposed in #46 is providing the `MediaIterator`. `MediaIterators` are stateful and I don't think the caller should be able to change the state of the iterator within the callback before returning it. For example, what is the expected outcome of seeking to an arbitrary frame within the callback, before returning control to the `janice_detect` function? 

I used `JaniceImage` as an alternative because it doesn't have this behavior, and I added the memory_io implementation to allow creating a MediaIterator directly from a `JaniceImage`. I used a rect, frame (and should have provided confidence) to allow the user to manually build a track, which they can use to create a detection.

This is not the only way that callbacks can be implemented. An alternative (based on your suggestion in #46)-

```
/*!
 * A callback function for immediate detection output. The callback is not
 * expected to be thread-safe.
 *
 * \param detection The detection object
 * \param user_data User defined data structure
 */
typedef JaniceError (*JaniceDetectionCallback)(const JaniceDetection*, void*);

/*!
 * A callback function for immediate detection output from a batch. The
 * callback is not expected to be thread-safe.
 *
 * \param detection The detection object
 * \param index The index of the input media iterator the detection is associated with
 * \param user_data User defined data structure
 */
typedef JaniceError (*JaniceBatchDetectionCallback)(const JaniceDetection*, size_t, void*);
```

The caller can map the detection back to the source iterator in both cases, and process the detections accordingly. This also maps to enrollment, as you suggested in #48, 

```
/*!
 * A callback function for immediate enrollment output. The callback is not
 * expected to be thread-safe.
 *
 * \param template The enrolled template
 * \param detection The detection object associated with the template
 * \param user_data User defined data structure
 */
typedef JaniceError (*JaniceEnrollMediaCallback)(const JaniceTemplate*, const JaniceDetection*, void*);

/*!
 * A callback function for immediate enrollment output from a batch. The
 * callback is not expected to be thread-safe.
 *
 * \param template The enrolled template
 * \param detection The detection object associated with the template
 * \param index The index of the input media iterator the detection is associated with
 * \param user_data User defined data structure
 */
typedef JaniceError (*JaniceBatchEnrollMediaCallback)(const JaniceTemplate*, const JaniceDetection*, size_t, void*);

/*!
 * A callback function for immediate enrollment output from a batch. The
 * callback is not expected to be thread-safe.
 *
 * \param template The enrolled template
 * \param uint64_t Optional template
 * \param index The index of the input media iterator the detection is associated with
 * \param user_data User defined data structure
 */
typedef JaniceError (*JaniceBatchEnrollDetectionsCallback)(const JaniceTemplate*, uint64_t, size_t, void*);
```

So my questions are 
1. Do you agree with the issues around passing `MediaIterators` to callbacks or do you see a different alternative?
2. If yes to 1, would you prefer moving forwards with the `JaniceImage` flavor of callbacks, the alternative approach or a third approach I haven't considered?

**Comment by taa01776** [comment]
- One would like to declare a subset of the media iterator operations as const--tell, get, is_video, get_frame_rate, get_physical_frame_rate--and pass a const media iterator to the callbacks. But this isn't C++, and anyway the implementations of tell() and get() aren't technically const, since they both initialize iterator state. I dunno, would sufficiently emphatic documentation (If you do this, your computer will immediately halt and catch fire, but please, don't let that stop you...) of this limitation be enough? I agree that the callback shouldn't be messing with the iterator, because the caller doesn't want to go through a whole save state / restore state every time there's a callback, but I still think the image by itself doesn't provide enough information. So yeah, I think the alternative is better than the JaniceImage form.
- The restriction on modifying the iterator applies whether it's passed directly from the callback or grabbed from the user data, so the emphatic doc is still required.
- Passing the JaniceDetection permits tracking if you want to do it in the callback, but also allows tracks to be passed directly, so that's better. It also allows frame numbers to be passed if the detection / track is in a video.
- Would it be worth it to generalize to a pair of callback declarations (one detection, one enrollment) with the extra arguments defaulted as appropriate? It's what will be happening once you get into the callback anyway...

**Comment by taa01776** [comment]
One more comment: the get_feature_vector API makes the assumption that a template is basically represented as a single array of numbers (1 x N, for some value of N). Some work we're doing now will, in some cases, invalidate that assumption. Presumably in such cases the API would return some kind of error, but it might be worthwhile thinking about what, if anything, API users would be able to do with the data returned by the call.

**Comment by JordanCheney** [comment]
@taa01776 can you review the callbacks for detection and enrollment? I made two callbacks for enrollment (enroll from media vs. enroll from detections).

**Comment by taa01776** [comment]
I take it that the size_t parameter to the callbacks will be 0 in the non-batch case, and the index into the JaniceMediaIterators for batch. This seems OK, given that there's enough information being passed to figure out where the callback came from.
Is there anything in the documentation about the semantics of the return value from the callback? One could at least imagine a couple of distinguished error values to tell the API to exit immediately (returning an error code, of course), or to exclude the thing that was just presented to the callback.

**Comment by taa01776** [comment]
Is there any specification of the correct handling of the JaniceErrors parameter to the various calls that take it? Specifically:
- Assume that a null value for that parameter is valid; in that case, it's just the current behavior. Is that correct?
- If the caller provides one, presumably it starts out empty, and the API will populate it? Or is the assumption that the caller will allocate a structure of the appropriate size?
- Is the assumption that the offset in the errors argument for detect_batch matches the offset in the media parameter? Same for batch enrollment? Needs to be very clear.

**Comment by JordanCheney** [comment]
The documented behavior for callbacks is to return 0 in the non-batch base as you suggested and for the parent to exit immediately if the callback doesn't return JANICE_SUCCESS.

For JaniceErrors, 

* The documented specification is that it is always passed as part of the call (it can't be nullptr) 
* The caller allocates the struct memory for the list but not the member pointer, which is expected to be allocated appropriately by the implementation. The implementation will also set the size appropriately
* Yes the errors offset should match the media offset for detect batch and enroll from media batch. For enroll from detections it should match the offset in the top level list. This should be clear in the documentation.

**Comment by taa01776** [comment]
Thanks for the updates.
I’d think correct behavior for a callback error return would be to return an error for the current offset in the JaniceErrors structure and continue with the next one. Is that what you mean?
There should be a distinguished error code that means, bail out all the way, not that anyone should return it.
              -ta

**Comment by JordanCheney** [comment]
@taa01776 that wasn't what I meant but I thought it was a good idea so I update the batch callback signatures. Now errors from the callback should be reported at the appropriate offset. The callback can return `JANICE_CALLBACK_EXIT_IMMEDIATELY` to indicate to the parent it wants to abort processing.

**Pull request merged**
