### PR TITLE
First pass at v6.0

### PR DESCRIPTION
**Pull request by JordanCheney**
@carlosdcastillo @taa01776 could you please review the changes I've made here and see if they satisfy the open issues? @taa01776 some of these changes conflict with your existing PR. If you could rebase you're changes to merge with this branch I can review and add them in. Please note, that the harness executables compile but my tests are still ongoing- I wanted to get your feedback quickly.

### CODE REVIEW

**Comment by carlosdcastillo** [comment]
I think this looks good.

**Comment by taa01776** [comment]
The sparse I/O implementation is useful, but I don’t quite understand some of the choices:

  *   It would be helpful if the frame number array could be defaulted to NULL—often (enough), that information has been lost, and a simple 0 – N-1 would be enough (obviously one has to provide the frames in time order, but that’s easier to do than not).
  *   Why no seek() and get()?

The JaniceContext change I think is a step in the right direction. Would also like to see a call to initialize a context *with parameters* (like the old JaniceCreateContext, but without allocating any memory).

Obviously I will continue to complain about all the structs that are passed by value. Why is that a good idea?

The outputs from the harnesses should, where it matters, match, or at least strictly superset, the evaluation protocol formats (e.g., detection output file should include a template ID, even if it’s just a line number; …).

When I get a second, I will submit a pull request to fix all the missing ;s after JANICE_ASSERT calls, but I’d request that use of them become a standard. There may be times when it’s reasonable to have code that’s not syntactically correct until it’s been preprocessed, but this isn’t one of them.

Argument parsing is better.
                -ta

**Comment by JordanCheney** [comment]
@taa01776 thanks for the feedback. Regarding spare media iterators, both you and @carlosdcastillo have suggested just using 0-(N-1) as frame numbers in the iterators. Could we drop the frame number parameter all together and just use 0-(N-1)? This is the reason I didn't implement `seek()` and `get()` initially. Given a sparse iterator with frames 0, 4, 8, and 12 should I `seek(2)` to get the second frame or `seek(8)`? If we agree on frame numbers being 0-(N-1) then seek() and get() are easy.

For `JaniceContext` I was anticipating users could do `context.role = ...` without needing another function. Would you prefer `janice_context_set_parameters(...)` or alternatively `janice_is_valid_context(...)` which would check if the set parameters are valid?

On the input structs passed by value. These could have been passed as pointers to save the copying overhead. At this point, I don't think changing this is worth the headache of breaking every function from 5.0 -> 6.0. The API structs are small and I'd expect any added overhead to be noticeable against the run time of the functions.

I'll update the harness to output the proper headers.

**Comment by taa01776** [comment]
WRT: passed by value: There’s also the overhead of figuring out whether a given parameter is being passed as a pointer or as a struct, which the current API include files cleverly obfuscate with their typedefs.
Also, given the number of incompatible changes already baked into this version, why not?

Not gonna worry about JaniceContext.

I’m fine with dropping the explicit frame numbers on sparse iterators—my own implementation (for the current release) doesn’t have them. If anyone ever needs such thing, he can just copy/paste/edit to get the needed functionality. Not quite as clean as subclassing, but so it goes.
                -ta

.csv

**Pull request merged**
