### PR TITLE
Modify harness CMake file to allow installation to parent 

### PR DESCRIPTION
**Pull request by taa01776**
I changed the harness CMakeLists.txt file to loop over the list of files (just like in the Janus src/utils directory). If JANICE_EVAL_HARNESS_INSTALL is defined, then it will be used as an installation destination for each of the harness executables.

### CODE REVIEW

**Comment by taa01776** [comment]
I added a couple more commits: the headers expected by some of the test harness files don't match either IJB-C or CS5, so I changed them. (Got tedious just testing janice_detect, and was only going to get worse.)

**Comment by JordanCheney** [comment]
@taa01776 Is this PR still relevant for you? If yes, could you fix the conflicts and I will review.

**Comment by taa01776** [comment]
The functionality still is, but the pull request is so old now… I’d suggest that you shoot it, and I’ll make a new one with whatever might still need to happen.
                -ta

**Comment by taa01776** [comment]
In fact, I just did a full diff of the current JanICE repo vs. that fork. There might be a couple of minor things that are worth moving over, but I'll pick those up somewhere else, after the current data call. You can just close (reject? whatever) this PR.

**Comment by JordanCheney** [comment]
Thanks!

**Pull request closed without merging**
